---
title: Início
output:
  html_document:
    toc: true
    css:
      - ./CSS/generic.css
      - ./CSS/logo-above-toc.css
      - ./CSS/main-color.css
      - ./CSS/narrow-margins.css
      - ./CSS/responsive.css
---

<!--install and/or load all R packages-->
```{r setup, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%", results = "hide"}
# restart all variables
rm(list = ls(all = TRUE))

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  results = "asis",
  include = TRUE,
  out.width = "100%",
  knitr.kable.NA = '',
  knitr.table.format = "html",
  webshot = "webshot",
  dev = "png"
)
source("Scripts/all-required-packages.R", local = knitr::knit_global())
```

```{r custom-yml, results = "hide"}
source("Scripts/custom-yml.R", local = knitr::knit_global())
```

```{r yaml-metadata, results = "hide"}
metadata$repository_url <- rmarkdown::metadata$repository_url
```

```{r update, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, results = "hide"}
# update all packages
update.packages(checkBuilt = TRUE, ask = FALSE)
```

```{r nojekyll, results = "hide"}
if(!file.exists(".nojekyll")) {
  file.create('.nojekyll')
}
```

```{r main-color, results = "hide"}
# read css color for this page
css <- cssparser::read_css("./CSS/main-color.css")
main.color <- css$`:root`$`--mybackgroundcolor`
```

<!--create (if non existent) all required folders-->
```{r check-create-folders, results = "hide"}
paths <- c(
  file.path(getwd(), "PPG"),
  file.path(getwd(), "Sucupira"),
  file.path(getwd(), "Impacto", "Sage Policy Profiles")
  )

for (i in 1:length(paths)) {
  if (!dir.exists(paths[i])) {
    dir.create(paths[i], recursive = TRUE, showWarnings = FALSE)
  }
}
```

<!--read METRIC files-->
```{r source-metrics-scripts, results = "hide"}
source(file.path("Scripts", "citescore.R"), local = knitr::knit_global())
source(file.path("Scripts", "sjr.R"), local = knitr::knit_global())
source(file.path("Scripts", "webqualis.R"), local = knitr::knit_global())

source("Scripts/doi-cleaner.R", local = knitr::knit_global())

source(file.path("Scripts", "get_citescore.R"),
       local = knitr::knit_global())
source(file.path("Scripts", "get_sjr.R"), local = knitr::knit_global())
source(file.path("Scripts", "get_webqualis.R"),
       local = knitr::knit_global())
# get metrics from Scopus, SCIMago and CAPES
source(file.path("Scripts", "get-metrics-from-sources.R"), local = knitr::knit_global())
```

<!--check Sucupira folder-->
```{r try-sucupira-files, results = "hide"}
files.to.read <-
  list.dirs(file.path(getwd(), "Sucupira"),
            full.names = TRUE,
            recursive = FALSE)
has.sucupira.files <- length(files.to.read) != 0
has.artigos.completos.sucupira <- FALSE
has.artigos.resumos.sucupira <- FALSE
has.anais.sucupira <- FALSE
has.livros.sucupira <- FALSE
has.producao.sucupira <- FALSE
has.2024.2021 <- FALSE
has.2020.2017 <- FALSE
has.2016.2013 <- FALSE
has.2012.2010 <- FALSE
has.posdocs <- FALSE
```

```{r try-periodos, results = "hide", eval = has.sucupira.files}
# get years
source("Scripts/years-sucupira.R")

# periodo
periodo <- 2021:min(as.numeric(format(Sys.Date(), "%Y")), 2024)
has.2024.2021 <- any(!is.na(match(periodo, anos)))

# periodo
periodo <- 2017:min(as.numeric(format(Sys.Date(), "%Y")), 2020)
has.2020.2017 <- any(!is.na(match(periodo, anos)))

# periodo
periodo <- 2013:min(as.numeric(format(Sys.Date(), "%Y")), 2016)
has.2016.2013 <- any(!is.na(match(periodo, anos)))

# periodo
periodo <- 2010:min(as.numeric(format(Sys.Date(), "%Y")), 2012)
has.2012.2010 <- any(!is.na(match(periodo, anos)))
```

<!--check PPG folder-->
```{r try-ppg-files, results = "hide"}
# list all PPG files
files.to.read <-
  list.dirs(file.path(getwd(), "PPG"),
            full.names = TRUE,
            recursive = FALSE)
has.ppg.files <- length(files.to.read) != 0
has.artigos.completos.ppg <- FALSE
has.artigos.resumos.ppg <- FALSE
has.producao.ppg <- FALSE
```

<!--check Impacto/Sage folder-->
```{r try-impacto-sage-files, results = "hide"}
# list all Sage Profiles
files.to.read <-
  list.files(file.path(getwd(), "Impacto", "Sage Policy Profiles"),
            full.names = TRUE,
            recursive = FALSE)
has.impacto.sage.files <- length(files.to.read) != 0
```

<!--check available files in PPG folder-->
```{r try-agendas-pesquisa, results = "hide"}
has.agendas.pesquisa <-
  !is.error(try(readxl::read_excel("PPG/Agendas de Pesquisa.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-apresentacao, results = "hide"}
has.apresentacao <-
  !is.error(try(readxl::read_excel("PPG/Apresentação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-area-capes, results = "hide"}
has.area.capes <-
  !is.error(try(readxl::read_excel("PPG/Área CAPES.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-autoavaliacoes, results = "hide"}
has.autoavaliacao <-
  !is.error(try(readxl::read_excel("PPG/Autoavaliação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-avaliacao, results = "hide"}
has.avaliacao <-
  !is.error(try(readxl::read_excel("PPG/Avaliação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-bibliografia, results = "hide"}
has.bibliografia <-
  !is.error(try(readxl::read_excel("PPG/Bibliografia.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-blog-externos, results = "hide"}
has.blogs.externos <-
  !is.error(try(readxl::read_excel("PPG/Blogs externos.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-blog-ies, results = "hide"}
has.blog.ies <-
  !is.error(try(readxl::read_excel("PPG/Blog institucional.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-bolsas, results = "hide"}
has.bolsas <-
  !is.error(try(readxl::read_excel("PPG/Bolsas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-calendarios, results = "hide"}
has.calendarios <-
  !is.error(try(readxl::read_excel("PPG/Calendários.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-cep, results = "hide"}
has.cep <-
  !is.error(try(readxl::read_excel("PPG/Comitê de Ética em Pesquisa.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-convenios, results = "hide"}
has.convenios <-
  !is.error(try(readxl::read_excel("PPG/Convênios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-cooperacoes, results = "hide"}
has.cooperacoes <-
  !is.error(try(readxl::read_excel("PPG/Cooperações.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-coordenacao, results = "hide"}
has.coordenacao <-
  !is.error(try(readxl::read_excel("PPG/Coordenação.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-dados-cadastrais, results = "hide"}
has.dados.cadastrais <-
  !is.error(try(readxl::read_excel("PPG/Dados Cadastrais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-destaques, results = "hide"}
has.destaques <-
  !is.error(try(readxl::read_excel("PPG/Destaques.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-discentes, results = "hide"}
has.discentes <-
  !is.error(try(readxl::read_excel("PPG/Discentes.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-downloads, results = "hide"}
has.downloads <-
  !is.error(try(readxl::read_excel("PPG/Downloads.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-editais, results = "hide"}
has.editais <-
  !is.error(try(readxl::read_excel("PPG/Editais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-financiadores, results = "hide"}
has.financiadores <-
  !is.error(try(readxl::read_excel("PPG/Financiadores.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-grupos-pesquisa, results = "hide"}
has.grupos.pesquisa <-
  !is.error(try(readxl::read_excel("PPG/Grupos de Pesquisa.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-historico, results = "hide"}
has.historico <-
  !is.error(try(readxl::read_excel("PPG/Histórico.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-infraestrutura, results = "hide"}
has.infraestrutura <-
  !is.error(try(readxl::read_excel("PPG/Infraestrutura.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-internacionalizacao, results = "hide"}
has.internacionalizacao <-
  !is.error(try(readxl::read_excel("PPG/Internacionalização.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-laboratorios, results = "hide"}
has.laboratorios <-
  !is.error(try(readxl::read_excel("PPG/Laboratórios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-metodologia, results = "hide"}
has.metodologia <-
  !is.error(try(readxl::read_excel("PPG/Metodologia.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-notas, results = "hide"}
has.notas <-
  !is.error(try(readxl::read_excel("PPG/Notas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-periodicos, results = "hide"}
has.periodicos <-
  !is.error(try(readxl::read_excel("PPG/Periódicos institucionais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-planejamento, results = "hide"}
has.planejamento <-
  !is.error(try(readxl::read_excel("PPG/Planejamento estratégico.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-podcasts, results = "hide"}
has.podcasts <-
  !is.error(try(readxl::read_excel("PPG/Podcasts.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-politicas, results = "hide"}
has.politicas <-
  !is.error(try(readxl::read_excel("PPG/Políticas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-premio-capes, results = "hide"}
has.premio.capes <-
  !is.error(try(readxl::read_excel("PPG/Prêmio CAPES de Tese.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-premios, results = "hide"}
has.premios <-
  !is.error(try(readxl::read_excel("PPG/Prêmios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-producao, results = "hide"}
has.producao <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-posdocs-sucupira, results = "hide", eval = has.sucupira.files}
# posdocs
sheet <- "Pós-Doc"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())

has.posdocs <- !sjmisc::is_empty(sucupira.raw)
```

```{r try-repositorios, results = "hide"}
has.repositorios.sede <-
  !is.error(try(readxl::read_excel("PPG/Repositórios.xlsx", sheet =  "Sede"),
                silent = TRUE)
  )
has.repositorios.cooperacao <-
  !is.error(try(readxl::read_excel("PPG/Repositórios.xlsx", sheet = "Cooperação"),
                silent = TRUE)
  )
```

```{r try-videos, results = "hide"}
has.videos <-
  !is.error(try(readxl::read_excel("PPG/Videos.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r ppg-data, results = "hide", eval = all(has.dados.cadastrais, has.sucupira.files)}
# projetos - membros
sheet <- "Docentes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())

source("Scripts/years-sucupira.R", local = knitr::knit_global())
names(sucupira.list) <- as.character(anos)

# most recent Sucupira year
most.recent <-
  as.character(ifelse(!is.null(sucupira.list[[format(Sys.Date(), "%Y")]]), format(Sys.Date(), "%Y"), max(as.numeric(
    names(sucupira.list)
  ))))

# read separate sheets
docentes.raw <- sucupira.list[[most.recent]]

# get initials from the PPG data
nome.PPG <- unique(docentes.raw$'Nome do PPG')

nome.PPG.split <- stringr::str_split_1(as.character(nome.PPG)[[1]], " ")
match.stopwords <-
  match(stringr::str_split_1(as.character(nome.PPG)[[1]], " "), tm::stopwords("portuguese"))
nome.PPG.no.stopwords <-
  paste(nome.PPG.split[is.na(match.stopwords)], collapse = " ")
source("Scripts/get-initials.R")
sigla.PPG <- initials(nome.PPG.no.stopwords)

try(site.PPG <-
  readxl::read_excel("PPG/Dados Cadastrais.xlsx",
             sheet = "Endereço",
             col_types = c("text"))[7, 2],
  silent = TRUE)

# qualquer planilha para obter os dados da IES
sheet <- "Docentes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())
nome.IES <- unique(sucupira.raw$`IES Nome`)
nome.IES <- tools::toTitleCase(as.character(nome.IES))

sigla.IES <- unique(sucupira.raw$`IES Sigla`)
```

```{r producao-sucupira, results = "hide", eval = has.sucupira.files}
# produções
sheet <- "Produções - Detalhes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())


# características
subtipo <- "ARTIGO EM PERIÓDICO"
detalhamento <- "Completo"
item.detalhamento <- c("Número do DOI", "URL do DOI", "URL")

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo &
    produtos$"Valor do Item de Detalhamento" == detalhamento])
titles <- titles[!is.na(titles)]

doi_artigos_completos_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_artigos_completos_sucupira <- rbind(
      doi_artigos_completos_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_artigos_completos_sucupira <-
    as.data.frame(doi_artigos_completos_sucupira[!is.na(doi_artigos_completos_sucupira)])
  names(doi_artigos_completos_sucupira) <- "DOI"
}
has.artigos.completos.sucupira <-
  !sjmisc::is_empty(doi_artigos_completos_sucupira)


# características
subtipo <- "ARTIGO EM PERIÓDICO"
detalhamento <- "Resumo"
item.detalhamento <- c("Número do DOI", "URL do DOI", "URL")

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (
  produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo & 
  produtos$"Valor do Item de Detalhamento" == detalhamento]
)
titles <- titles[!is.na(titles)]

doi_artigos_resumos_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_artigos_resumos_sucupira <- rbind(
      doi_artigos_resumos_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_artigos_resumos_sucupira <-
    as.data.frame(doi_artigos_resumos_sucupira[!is.na(doi_artigos_resumos_sucupira)])
  names(doi_artigos_resumos_sucupira) <- "DOI"
}
has.artigos.resumos.sucupira <-
  !sjmisc::is_empty(doi_artigos_resumos_sucupira)


# características
subtipo <- "TRABALHO EM ANAIS"
item.detalhamento <- "URL"

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (
  produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo]
)
titles <- titles[!is.na(titles)]

doi_anais_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_anais_sucupira <- rbind(
      doi_artigos_resumos_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_anais_sucupira <-
    as.data.frame(doi_anais_sucupira[!is.na(doi_anais_sucupira)])
  names(doi_anais_sucupira) <- "DOI"
}
has.anais.sucupira <-
  !sjmisc::is_empty(doi_anais_sucupira)


# características
subtipo <- "LIVROS"
item.detalhamento <- "URL"

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (
  produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo]
)
titles <- titles[!is.na(titles)]

doi_livros_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_livros_sucupira <- rbind(
      doi_artigos_resumos_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_livros_sucupira <-
    as.data.frame(doi_livros_sucupira[!is.na(doi_livros_sucupira)])
  names(doi_livros_sucupira) <- "DOI"
}
has.livros.sucupira <-
  !sjmisc::is_empty(doi_livros_sucupira)


has.producao.sucupira <-
  any(has.artigos.completos.sucupira,
      has.artigos.resumos.sucupira,
      has.anais.sucupira,
      has.livros.sucupira)
```

```{r producao-ppg, results = "hide"}
has.artigos.completos.ppg <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.completos"),
                silent = TRUE))
if(!has.artigos.completos.ppg){
  doi_with_altmetric_artigos = data.frame()
  doi_without_altmetric_artigos = data.frame()
  references_artigos = data.frame()
  doi_with_altmetric_artigos_impacto = data.frame()
  doi_without_altmetric_artigos_impacto = data.frame()
  references_artigos_impacto = data.frame()
  }

has.artigos.resumos.ppg <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.resumos"), silent = TRUE))
if(!has.artigos.resumos.ppg){
  doi_with_altmetric_resumos = data.frame()
  doi_without_altmetric_resumos = data.frame()
  references_resumos = data.frame()
  doi_with_altmetric_resumos_impacto = data.frame()
  doi_without_altmetric_resumos_impacto = data.frame()
  references_resumos_impacto = data.frame()
  }

has.preprints.ppg <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.preprints"),
                silent = TRUE))
if(!has.preprints.ppg){
  doi_with_altmetric_preprints = data.frame()
  doi_without_altmetric_preprints = data.frame()
  references_preprints = data.frame()
  doi_with_altmetric_preprints_impacto = data.frame()
  doi_without_altmetric_preprints_impacto = data.frame()
  references_preprints_impacto = data.frame()
  }

has.livros.ppg <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.livros"), silent = TRUE))
if(!has.livros.ppg){
  doi_with_altmetric_livros = data.frame()
  doi_without_altmetric_livros = data.frame()
  references_livros = data.frame()
  doi_with_altmetric_livros_impacto = data.frame()
  doi_without_altmetric_livros_impacto = data.frame()
  references_livros_impacto = data.frame()
  }

has.capitulos.ppg <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.capitulos"), silent = TRUE))
if(!has.capitulos.ppg){
  doi_with_altmetric_capitulos = data.frame()
  doi_without_altmetric_capitulos = data.frame()
  references_capitulos = data.frame()
  doi_with_altmetric_capitulos_impacto = data.frame()
  doi_without_altmetric_capitulos_impacto = data.frame()
  references_capitulos_impacto = data.frame()
  }

has.anais.ppg <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.anais"), silent = TRUE))
if(!has.anais.ppg){
  doi_with_altmetric_anais = data.frame()
  doi_without_altmetric_anais = data.frame()
  references_anais = data.frame()
  doi_with_altmetric_anais_impacto = data.frame()
  doi_without_altmetric_anais_impacto = data.frame()
  references_anais_impacto = data.frame()
}

has.producao.ppg <-
  any(has.artigos.completos.ppg,
      has.artigos.resumos.ppg,
      has.preprints.ppg,
      has.livros.ppg,
      has.capitulos.ppg,
      has.anais.ppg)
```

```{r metrics-artigos-completos, results = "hide", cache = TRUE, cache.path = "cache/artigos-completos/", eval = any(has.artigos.completos.ppg, has.artigos.completos.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if(has.artigos.completos.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "PI.completos",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if(has.artigos.completos.sucupira) {
  dois.sucupira <- doi_artigos_completos_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if(!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R",
         local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_artigos <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_artigos <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_artigos$doi,
        doi_without_altmetric_artigos$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  names(formatted_citations) <- c("ID", "Reference")
  
  references_artigos <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_artigos = data.frame()
  doi_without_altmetric_artigos = data.frame()
  references_artigos = data.frame()
  doi_with_altmetric_artigos_impacto = data.frame()
  doi_without_altmetric_artigos_impacto = data.frame()
  references_artigos_impacto = data.frame()
}
```

```{r metrics-artigos-resumos, results = "hide", cache = TRUE, cache.path = "cache/artigos-resumos/", eval = any(has.artigos.resumos.ppg, has.artigos.resumos.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if (has.artigos.resumos.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "PI.resumos",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if (has.artigos.resumos.sucupira) {
  dois.sucupira <- doi_artigos_resumos_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R",
         local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_resumos <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_resumos <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_resumos$doi,
        doi_without_altmetric_resumos$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  names(formatted_citations) <- c("ID", "Reference")
  
  references_resumos <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_resumos = data.frame()
  doi_without_altmetric_resumos = data.frame()
  references_resumos = data.frame()
  doi_with_altmetric_resumos_impacto = data.frame()
  doi_without_altmetric_resumos_impacto = data.frame()
  references_resumos_impacto = data.frame()
}
```

```{r metrics-preprints, results = "hide", cache = TRUE, cache.path = "cache/preprints/", eval = has.preprints.ppg}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.preprints",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R",
         local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_preprints <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_preprints <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_preprints$doi,
        doi_without_altmetric_preprints$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  names(formatted_citations) <- c("ID", "Reference")
  
  references_preprints <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_preprints = data.frame()
  doi_without_altmetric_preprints = data.frame()
  references_preprints = data.frame()
  doi_with_altmetric_preprints_impacto = data.frame()
  doi_without_altmetric_preprints_impacto = data.frame()
  references_preprints_impacto = data.frame()
}
```

```{r metrics-livros, results = "hide", cache = TRUE, cache.path = "cache/livros/", eval = any(has.livros.ppg, has.livros.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if(has.livros.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "PI.livros",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if(has.livros.sucupira) {
  dois.sucupira <- doi_livros_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R",
         local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_livros <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_livros <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_livros$doi,
        doi_without_altmetric_livros$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  names(formatted_citations) <- c("ID", "Reference")
  
  references_livros <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_livros = data.frame()
  doi_without_altmetric_livros = data.frame()
  references_livros = data.frame()
  doi_with_altmetric_livros_impacto = data.frame()
  doi_without_altmetric_livros_impacto = data.frame()
  references_livros_impacto = data.frame()
}
```

```{r metrics-capitulos, results = "hide", cache = TRUE, cache.path = "cache/capitulos/", eval = has.capitulos.ppg}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.capitulos",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R",
         local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_capitulos <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_capitulos <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_capitulos$doi,
        doi_without_altmetric_capitulos$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  names(formatted_citations) <- c("ID", "Reference")
  
  references_capitulos <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_capitulos = data.frame()
  doi_without_altmetric_capitulos = data.frame()
  references_capitulos = data.frame()
  doi_with_altmetric_capitulos_impacto = data.frame()
  doi_without_altmetric_capitulos_impacto = data.frame()
  references_capitulos_impacto = data.frame()
}
```

```{r metrics-anais, results = "hide", cache = TRUE, cache.path = "cache/anais/", eval = any(has.anais.ppg, has.anais.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if(has.anais.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "PI.anais",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if(has.anais.ppg) {
  dois.sucupira <- doi_anais_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R",
         local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_anais <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_anais <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_anais$doi,
        doi_without_altmetric_anais$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  names(formatted_citations) <- c("ID", "Reference")
  
  references_anais <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_anais = data.frame()
  doi_without_altmetric_anais = data.frame()
  references_anais = data.frame()
  doi_with_altmetric_anais_impacto = data.frame()
  doi_without_altmetric_anais_impacto = data.frame()
  references_anais_impacto = data.frame()
}
```

```{r bind-all, results = "hide", cache = TRUE, cache.path = "cache/bind-all/", eval = any(has.producao.sucupira, has.producao.ppg)}

# bind sources
doi_with_altmetric_all <-
  dplyr::bind_rows(
    doi_with_altmetric_artigos,
    doi_with_altmetric_resumos,
    doi_with_altmetric_preprints,
    doi_with_altmetric_livros,
    doi_with_altmetric_capitulos,
    doi_with_altmetric_anais
  ) %>%
  as.data.frame()

# bind sources
doi_without_altmetric_all <-
  dplyr::bind_rows(
    doi_without_altmetric_artigos,
    doi_without_altmetric_resumos,
    doi_without_altmetric_preprints,
    doi_without_altmetric_livros,
    doi_without_altmetric_capitulos,
    doi_without_altmetric_anais
  ) %>%
  as.data.frame()

# bind common data
doi_all <-
  dplyr::bind_rows(doi_with_altmetric_all,
                   doi_without_altmetric_all) %>%
  as.data.frame()

references_all <-
  dplyr::bind_rows(
    references_artigos,
    references_resumos,
    references_preprints,
    references_livros,
    references_capitulos,
    references_anais
  ) %>%
  data.frame()
```

```{r retratacoes, results = "hide", cache = TRUE, cache.path = "cache/retratacoes/", eval = any(has.producao.sucupira, has.producao.ppg)}
doi_with_altmetric_retracted <- c()
if (!sjmisc::is_empty(doi_with_altmetric_all)) {
  for (i in 1:dim(doi_with_altmetric_all)[1]) {
    if (!retractcheck::check_doi(doi = as.character(doi_with_altmetric_all$doi[i]))) {
      doi_with_altmetric_retracted <-
        rbind(doi_with_altmetric_retracted,
              doi_with_altmetric_all[i,])
    }
  }
}

doi_without_altmetric_retracted <- c()
if (!sjmisc::is_empty(doi_without_altmetric_all)) {
  for (i in 1:dim(doi_without_altmetric_all)[1]) {
    if (!retractcheck::check_doi(doi = as.character(doi_without_altmetric_all$doi[i]))) {
      doi_without_altmetric_retracted <-
        rbind(doi_without_altmetric_retracted,
              doi_without_altmetric_all[i,])
    }
  }
}
```

```{r has, results = "hide", cache = TRUE, cache.path = "cache/has/"}
# directories
as.logical(has.sucupira.files)
as.logical(has.ppg.files)
as.logical(has.impacto.sage.files)

# PPG files
as.logical(has.agendas.pesquisa)
as.logical(has.apresentacao)
as.logical(has.area.capes)
as.logical(has.autoavaliacao)
as.logical(has.avaliacao)
as.logical(has.bibliografia)
as.logical(has.blogs.externos)
as.logical(has.blog.ies)
as.logical(has.bolsas)
as.logical(has.calendarios)
as.logical(has.cep)
as.logical(has.convenios)
as.logical(has.cooperacoes)
as.logical(has.coordenacao)
as.logical(has.dados.cadastrais)
as.logical(has.destaques)
as.logical(has.discentes)
as.logical(has.downloads)
as.logical(has.editais)
as.logical(has.financiadores)
as.logical(has.grupos.pesquisa)
as.logical(has.historico)
as.logical(has.infraestrutura)
as.logical(has.internacionalizacao)
as.logical(has.laboratorios)
as.logical(has.metodologia)
as.logical(has.notas)
as.logical(has.periodicos)
as.logical(has.planejamento)
as.logical(has.podcasts)
as.logical(has.politicas)
as.logical(has.premios)
as.logical(has.premio.capes)
as.logical(has.producao)
as.logical(has.repositorios.cooperacao)
as.logical(has.repositorios.sede)
as.logical(has.videos)

# data sucupira
as.logical(has.artigos.completos.sucupira)
as.logical(has.artigos.resumos.sucupira)
as.logical(has.livros.sucupira)
as.logical(has.anais.sucupira)
as.logical(has.producao.sucupira)
as.logical(has.2024.2021)
as.logical(has.2020.2017)
as.logical(has.2016.2013)
as.logical(has.2012.2010)
as.logical(has.posdocs)

# data ppg
as.logical(has.artigos.completos.ppg)
as.logical(has.artigos.resumos.ppg)
as.logical(has.preprints.ppg)
as.logical(has.livros.ppg)
as.logical(has.capitulos.ppg)
as.logical(has.anais.ppg)
as.logical(has.producao.ppg)
```

```{r save, results = "hide", eval = FALSE}
try(write.table(
  doi_with_altmetric_all,
  "doi_with_altmetric_all.tsv",
  quote = FALSE,
  sep = "\t",
  row.names = FALSE,
  col.names = TRUE
),
silent = TRUE)

try(write.table(
  doi_without_altmetric_all,
  "doi_without_altmetric_all.tsv",
  quote = FALSE,
  sep = "\t",
  row.names = FALSE,
  col.names = TRUE
),
silent = TRUE)

try(write.table(
  doi_all,
  "doi_all.tsv",
  quote = FALSE,
  sep = "\t",
  row.names = FALSE,
  col.names = TRUE
),
silent = TRUE
)
```
