---
title: Início
output:
  html_document:
    toc: true
    toc_float: true
    css:
      - ./CSS/generic.css
      - ./CSS/logo-above-toc.css
      - ./CSS/main-color.css
      - ./CSS/narrow-margins.css
      - ./CSS/responsive.css
---

<!--set up-->
```{r setup, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%", results = "hide"}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  results = "asis",
  include = TRUE,
  out.width = "100%",
  knitr.kable.NA = '',
  knitr.table.format = ifelse(knitr::is_html_output(), "html", "latex"),
  webshot = "webshot",
  dev = "png"
)
```

<!--start-->
```{r start, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%"}
# restart all variables
rm(list = ls(all = TRUE))
```

<!--install and/or load all packages-->
```{r install-update-packages, echo = FALSE, include = FALSE}
source("Scripts/all-required-packages.R", local = knitr::knit_global())
```

```{r custom-yaml, eval = FALSE}
source("Scripts/custom-yaml.R", local = knitr::knit_global())
```

```{r yml-metadata}
metadata <- c()
metadata$repository_url <- yaml::read_yaml("_site.yml")$repository_url
```

```{r nojekyll}
if(!file.exists(".nojekyll")) {
  file.create('.nojekyll')
}
```

```{r main-color}
# read css color for this page
css <- cssparser::read_css("./CSS/main-color.css")
main.color <- css$`:root`$`--mybackgroundcolor`
```

<!--create (if non existent) all required folders-->
```{r check-create-folders}
paths <- c(
  file.path(getwd(), "PPG"),
  file.path(getwd(), "Sucupira"),
  file.path(getwd(), "Impacto", "Sage Policy Profiles")
)

for (i in 1:length(paths)) {
  if (!dir.exists(paths[i])) {
    dir.create(paths[i], recursive = TRUE, showWarnings = FALSE)
  }
}
```

<!--read METRIC files-->
```{r source-metrics-scripts}
source(file.path("Scripts", "citescore.R"), local = knitr::knit_global())
source(file.path("Scripts", "sjr.R"), local = knitr::knit_global())
source(file.path("Scripts", "webqualis.R"), local = knitr::knit_global())

source(file.path("Scripts", "doi-cleaner.R"), local = knitr::knit_global())

source(file.path("Scripts", "get-citescore.R"), local = knitr::knit_global())
source(file.path("Scripts", "get-sjr.R"), local = knitr::knit_global())
source(file.path("Scripts", "get-webqualis.R"), local = knitr::knit_global())
source(file.path("Scripts", "get-metrics-from-sources.R"), local = knitr::knit_global())
```

<!--check Sucupira folder-->
```{r try-sucupira-files}
files.to.read <-
  list.files(file.path(getwd(), "Sucupira"),
            full.names = TRUE,
            recursive = TRUE,
            pattern = "xlsx"
)
has.sucupira.files <- length(files.to.read) != 0
has.artigos.completos.sucupira <- FALSE
has.editoria.sucupira <- FALSE
has.anais.sucupira <- FALSE
has.livros.sucupira <- FALSE
has.producao.sucupira <- FALSE
has.2024.2021 <- FALSE
has.2020.2017 <- FALSE
has.2016.2013 <- FALSE
has.2012.2010 <- FALSE
has.posdocs <- FALSE
has.retratacoes <- FALSE
```

```{r try-periodos, eval = has.sucupira.files}
# get years
source("Scripts/years-sucupira.R", local = knitr::knit_global())

# periodo
periodo <- 2021:min(as.numeric(format(Sys.Date(), "%Y")), 2024)
has.2024.2021 <- any(!is.na(match(periodo, anos)))

# periodo
periodo <- 2017:min(as.numeric(format(Sys.Date(), "%Y")), 2020)
has.2020.2017 <- any(!is.na(match(periodo, anos)))

# periodo
periodo <- 2013:min(as.numeric(format(Sys.Date(), "%Y")), 2016)
has.2016.2013 <- any(!is.na(match(periodo, anos)))

# periodo
periodo <- 2010:min(as.numeric(format(Sys.Date(), "%Y")), 2012)
has.2012.2010 <- any(!is.na(match(periodo, anos)))
```

<!--check PPG folder-->
```{r try-ppg-files}
# list all PPG files
files.to.read <-
  list.files(file.path(getwd(), "PPG"),
            full.names = TRUE,
            recursive = TRUE,
            pattern = "xlsx")
has.ppg.files <- length(files.to.read) != 0
has.artigos.completos.ppg <- FALSE
has.editoria.ppg <- FALSE
has.producao.ppg <- FALSE
```

<!--check Impacto/Sage folder-->
```{r try-impacto-sage-files}
# list all Sage Profiles
files.to.read <-
  list.files(file.path(getwd(), "Impacto", "Sage Policy Profiles"),
            full.names = TRUE,
            recursive = FALSE,
            pattern = ".csv")
has.impacto.sage.files <- length(files.to.read) != 0
```

<!--check available files in PPG folder-->
```{r try-agendas-pesquisa}
has.agendas.pesquisa <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Agendas de Pesquisa.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-apresentacao}
has.apresentacao <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Apresentação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-area-capes}
has.area.capes <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Área CAPES.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-autoavaliacoes}
has.autoavaliacao <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Autoavaliação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-avaliacao}
has.avaliacao <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Avaliação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-bibliografia}
has.bibliografia <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Bibliografia.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-blog-externos}
has.blogs.externos <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Blogs externos.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-blog-ies}
has.blog.ies <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Blog institucional.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-bolsas}
has.bolsas <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Bolsas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-calendarios}
has.calendarios <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Calendários.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-cep}
has.cep <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Comitê de Ética em Pesquisa.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-convenios}
has.convenios <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Convênios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-cooperacoes}
has.cooperacoes <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Cooperações.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-coordenacao}
has.coordenacao <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Coordenação.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-dados-cadastrais}
has.dados.cadastrais <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Dados Cadastrais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-destaques}
has.destaques <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Destaques.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-discentes}
has.discentes <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Discentes.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-downloads}
has.downloads <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Downloads.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-editais}
has.editais <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Editais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-financiadores}
has.financiadores <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Financiadores.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-grupos-pesquisa}
has.grupos.pesquisa <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Grupos de Pesquisa.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-historico}
has.historico <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Histórico.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-infraestrutura}
has.infraestrutura <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Infraestrutura.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-internacionalizacao}
has.internacionalizacao <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Internacionalização.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-laboratorios}
has.laboratorios <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Laboratórios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-metodologia}
has.metodologia <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Metodologia.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-notas}
has.notas <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Notas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-periodicos}
has.periodicos <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Periódicos institucionais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-planejamento}
has.planejamento <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Planejamento estratégico.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-podcasts}
has.podcasts <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Podcasts.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-politicas}
has.politicas <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Políticas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-premio-capes}
has.premio.capes <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Prêmio CAPES de Tese.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-premios}
has.premios <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Prêmios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-producao}
has.producao <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-posdocs-sucupira, eval = has.sucupira.files}
# posdocs
sheet <- "Pós-Doc"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())

has.posdocs <- !sjmisc::is_empty(sucupira.raw)
```

```{r try-repositorios}
has.repositorios.sede <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Repositórios.xlsx", sheet =  "Sede"),
                silent = TRUE)
  )
has.repositorios.cooperacao <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Repositórios.xlsx", sheet = "Cooperação"),
                silent = TRUE)
  )
```

```{r try-videos}
has.videos <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Videos.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r ppg-data, eval = all(has.dados.cadastrais, has.sucupira.files)}
# projetos - membros
sheet <- "Docentes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())

source("Scripts/years-sucupira.R", local = knitr::knit_global())
names(sucupira.list) <- as.character(anos)

# most recent Sucupira year
most.recent <-
  as.character(ifelse(!is.null(sucupira.list[[format(Sys.Date(), "%Y")]]), format(Sys.Date(), "%Y"), max(as.numeric(
    names(sucupira.list)
  ))))

# read separate sheets
docentes.raw <- sucupira.list[[most.recent]]

# get initials from the PPG data
nome.PPG <- unique(docentes.raw$'Nome do PPG')

nome.PPG.split <- stringr::str_split_1(as.character(nome.PPG)[[1]], " ")
match.stopwords <- match(stringr::str_split_1(as.character(nome.PPG)[[1]], " "), tm::stopwords("portuguese"))
nome.PPG.no.stopwords <- paste(nome.PPG.split[is.na(match.stopwords)], collapse = " ")
source("Scripts/get-initials.R", local = knitr::knit_global())
sigla.PPG <- initials(nome.PPG.no.stopwords)

try(site.PPG <-
  readxl::read_excel("PPG/Dados Cadastrais.xlsx",
             sheet = "Endereço",
             col_types = c("text"))[7, 2],
  silent = TRUE)

# qualquer planilha para obter os dados da IES
sheet <- "Docentes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())
nome.IES <- unique(sucupira.raw$`IES Nome`)
nome.IES <- tools::toTitleCase(as.character(nome.IES))

sigla.IES <- unique(sucupira.raw$`IES Sigla`)
```

```{r producao-sucupira, eval = has.sucupira.files}
# produções
sheet <- "Produções - Detalhes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())


# características
subtipo <- "ARTIGO EM PERIÓDICO"
detalhamento <- "Completo"
item.detalhamento <- c("Número do DOI", "URL do DOI", "URL")

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo &
    produtos$"Valor do Item de Detalhamento" == detalhamento])
titles <- titles[!is.na(titles)]

doi_artigos_completos_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_artigos_completos_sucupira <- rbind(
      doi_artigos_completos_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_artigos_completos_sucupira <-
    as.data.frame(doi_artigos_completos_sucupira[!is.na(doi_artigos_completos_sucupira)])
  names(doi_artigos_completos_sucupira) <- "DOI"
}
has.artigos.completos.sucupira <-
  !sjmisc::is_empty(doi_artigos_completos_sucupira)


# características
subtipo <- "ARTIGO EM PERIÓDICO"
detalhamento <- "Resumo"
item.detalhamento <- c("Número do DOI", "URL do DOI", "URL")

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (
  produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo & 
  produtos$"Valor do Item de Detalhamento" == detalhamento]
)
titles <- titles[!is.na(titles)]

doi_editoria_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_editoria_sucupira <- rbind(
      doi_editoria_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_editoria_sucupira <-
    as.data.frame(doi_editoria_sucupira[!is.na(doi_editoria_sucupira)])
  names(doi_editoria_sucupira) <- "DOI"
}
has.editoria.sucupira <-
  !sjmisc::is_empty(doi_editoria_sucupira)


# características
subtipo <- "TRABALHO EM ANAIS"
item.detalhamento <- "URL"

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (
  produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo]
)
titles <- titles[!is.na(titles)]

doi_anais_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_anais_sucupira <- rbind(
      doi_anais_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_anais_sucupira <-
    as.data.frame(doi_anais_sucupira[!is.na(doi_anais_sucupira)])
  names(doi_anais_sucupira) <- "DOI"
}
has.anais.sucupira <-
  !sjmisc::is_empty(doi_anais_sucupira)


# características
subtipo <- "LIVROS"
item.detalhamento <- "URL"

# Data selection
produtos <-
  sucupira.raw %>% dplyr::select(
    c(
      "Nome da Produção",
      "Subtipo de Produção",
      "Item de Detalhamento",
      "Valor do Item de Detalhamento"
    )
  )
# find titles of artigos completos
titles <- (
  produtos$"Nome da Produção"[
  produtos$"Subtipo de Produção" == subtipo]
)
titles <- titles[!is.na(titles)]

doi_livros_sucupira <- data.frame()
if (dim(produtos)[1] != 0) {
  # data filter
  for (i in 1:length(titles)) {
    idx1 <- produtos$`Nome da Produção` %in% titles[i]
    idx2 <- produtos$`Item de Detalhamento` %in% item.detalhamento
    idx <- and(idx1, idx2)
    doi_livros_sucupira <- rbind(
      doi_livros_sucupira,
      produtos$`Valor do Item de Detalhamento`[which(idx == TRUE)]
    )
  }
  doi_livros_sucupira <-
    as.data.frame(doi_livros_sucupira[!is.na(doi_livros_sucupira)])
  names(doi_livros_sucupira) <- "DOI"
}
has.livros.sucupira <-
  !sjmisc::is_empty(doi_livros_sucupira)


has.producao.sucupira <-
  any(has.artigos.completos.sucupira,
      has.editoria.sucupira,
      has.anais.sucupira,
      has.livros.sucupira)
```

```{r producao-ppg}
has.artigos.completos.ppg <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "artigos-completos"),
                silent = TRUE))
if(!has.artigos.completos.ppg){
  doi_with_altmetric_artigos = data.frame()
  doi_without_altmetric_artigos = data.frame()
  references_artigos = data.frame()
  doi_with_altmetric_artigos_impacto = data.frame()
  doi_without_altmetric_artigos_impacto = data.frame()
  references_artigos_impacto = data.frame()
  }

has.editoria.ppg <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "editorias"), silent = TRUE))
if(!has.editoria.ppg){
  doi_with_altmetric_editoria = data.frame()
  doi_without_altmetric_editoria = data.frame()
  references_editoria = data.frame()
  doi_with_altmetric_editoria_impacto = data.frame()
  doi_without_altmetric_editoria_impacto = data.frame()
  references_editoria_impacto = data.frame()
  }

has.livros.ppg <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "livros"), silent = TRUE))
if(!has.livros.ppg){
  doi_with_altmetric_livros = data.frame()
  doi_without_altmetric_livros = data.frame()
  references_livros = data.frame()
  doi_with_altmetric_livros_impacto = data.frame()
  doi_without_altmetric_livros_impacto = data.frame()
  references_livros_impacto = data.frame()
  }

has.anais.ppg <-
  !BBmisc::is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "trabalhos-anais"), silent = TRUE))
if(!has.anais.ppg){
  doi_with_altmetric_anais = data.frame()
  doi_without_altmetric_anais = data.frame()
  references_anais = data.frame()
  doi_with_altmetric_anais_impacto = data.frame()
  doi_without_altmetric_anais_impacto = data.frame()
  references_anais_impacto = data.frame()
}

has.producao.ppg <-
  any(has.artigos.completos.ppg,
      has.editoria.ppg,
      has.livros.ppg,
      has.anais.ppg)
```

```{r metrics-artigos-completos, cache = TRUE, cache.path = "cache/artigos-completos/", eval = any(has.artigos.completos.ppg, has.artigos.completos.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if(has.artigos.completos.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "artigos-completos",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if(has.artigos.completos.sucupira) {
  dois.sucupira <- doi_artigos_completos_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if(!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_artigos <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_artigos <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_artigos$doi,
        doi_without_altmetric_artigos$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  colnames(formatted_citations) <- c("ID", "Reference")
  
  references_artigos <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_artigos = data.frame()
  doi_without_altmetric_artigos = data.frame()
  references_artigos = data.frame()
  doi_with_altmetric_artigos_impacto = data.frame()
  doi_without_altmetric_artigos_impacto = data.frame()
  references_artigos_impacto = data.frame()
}
```

```{r metrics-editoria, cache = TRUE, cache.path = "cache/editoria/", eval = any(has.editoria.ppg, has.editoria.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if (has.editoria.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "editorias",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if (has.editoria.sucupira) {
  dois.sucupira <- doi_editoria_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_editoria <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_editoria <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_editoria$doi,
        doi_without_altmetric_editoria$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  colnames(formatted_citations) <- c("ID", "Reference")
  
  references_editoria <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_editoria = data.frame()
  doi_without_altmetric_editoria = data.frame()
  references_editoria = data.frame()
  doi_with_altmetric_editoria_impacto = data.frame()
  doi_without_altmetric_editoria_impacto = data.frame()
  references_editoria_impacto = data.frame()
}
```

```{r metrics-livros, cache = TRUE, cache.path = "cache/livros/", eval = any(has.livros.ppg, has.livros.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if(has.livros.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "livros",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if(has.livros.sucupira) {
  dois.sucupira <- doi_livros_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_livros <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_livros <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_livros$doi,
        doi_without_altmetric_livros$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  colnames(formatted_citations) <- c("ID", "Reference")
  
  references_livros <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_livros = data.frame()
  doi_without_altmetric_livros = data.frame()
  references_livros = data.frame()
  doi_with_altmetric_livros_impacto = data.frame()
  doi_without_altmetric_livros_impacto = data.frame()
  references_livros_impacto = data.frame()
}
```

```{r metrics-anais, cache = TRUE, cache.path = "cache/anais/", eval = any(has.anais.ppg, has.anais.sucupira)}
# bind PPG and SUCUPIRA DOIs
dois.ppg <- data.frame()
if(has.anais.ppg) {
  # read data
  data.sheet <-
    data.frame(readxl::read_excel(
      "PPG/Produção.xlsx",
      sheet = "trabalhos-anais",
      col_types = c("text")
    ))
  # select DOI column
  dois.ppg <-
    data.frame(DOI = data.sheet[, match("DOI", names(data.sheet))])
}
dois.sucupira <- data.frame()
if(has.anais.ppg) {
  dois.sucupira <- doi_anais_sucupira
}
dois <- data.frame(DOI = c(dois.sucupira$DOI, dois.ppg$DOI))

# limpa as entradas de DOI
dois <- doi_cleaner(dois)

# Data cleaning
dois <- data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = dois$DOI[!is.na(dois$DOI)])

if (!sjmisc::is_empty(dois)) {
  # cria metadados para rastreio pelo Altmetric
  source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())
  
  # get metrics from Altmetric and CrossRef
  source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())
  
  # store to use downstream
  doi_with_altmetric_anais <-
    get_metrics(
      doi_with_altmetric = doi_with_altmetric,
      doi_without_altmetric = NULL,
      citescore,
      scimago,
      qualis
    )
  doi_without_altmetric_anais <-
    get_metrics(
      doi_with_altmetric = NULL,
      doi_without_altmetric = doi_without_altmetric,
      citescore,
      scimago,
      qualis
    )
  
  # obtain formatted references
  formatted_citations <-
    rcrossref::cr_cn(
      c(
        doi_with_altmetric_anais$doi,
        doi_without_altmetric_anais$doi
      ),
      format = "text",
      raw = TRUE,
      style = "american-medical-association"
    )
  formatted_citations <- substring(formatted_citations, 3)
  formatted_citations <-
    cbind(seq(1, length(formatted_citations)), formatted_citations)
  colnames(formatted_citations) <- c("ID", "Reference")
  
  references_anais <- formatted_citations %>%
    data.frame()
} else {
  doi_with_altmetric_anais = data.frame()
  doi_without_altmetric_anais = data.frame()
  references_anais = data.frame()
  doi_with_altmetric_anais_impacto = data.frame()
  doi_without_altmetric_anais_impacto = data.frame()
  references_anais_impacto = data.frame()
}
```

```{r bind-all, cache = TRUE, cache.path = "cache/bind-all/", eval = any(has.producao.sucupira, has.producao.ppg)}
# recall for cache
doi_with_altmetric_artigos <- doi_with_altmetric_artigos
doi_with_altmetric_editoria <- doi_with_altmetric_editoria
doi_with_altmetric_livros <- doi_with_altmetric_livros
doi_with_altmetric_anais <- doi_with_altmetric_anais

# bind sources
doi_with_altmetric_all <-
  dplyr::bind_rows(
    doi_with_altmetric_artigos,
    doi_with_altmetric_editoria,
    doi_with_altmetric_livros,
    doi_with_altmetric_anais
  ) %>%
  as.data.frame()

# recall for cache
doi_without_altmetric_artigos <- doi_without_altmetric_artigos
doi_without_altmetric_editoria <- doi_without_altmetric_editoria
doi_without_altmetric_livros <- doi_without_altmetric_livros
doi_without_altmetric_anais <- doi_without_altmetric_anais

# bind sources
doi_without_altmetric_all <-
  dplyr::bind_rows(
    doi_without_altmetric_artigos,
    doi_without_altmetric_editoria,
    doi_without_altmetric_livros,
    doi_without_altmetric_anais
  ) %>%
  as.data.frame()

# bind common data
doi_all <-
  dplyr::bind_rows(doi_with_altmetric_all,
                   doi_without_altmetric_all) %>%
  as.data.frame()

# recall for cache
references_artigos <- references_artigos
references_editoria <- references_editoria
references_livros <- references_livros
references_anais <- references_anais

# bind common data
references_all <-
  dplyr::bind_rows(
    references_artigos,
    references_editoria,
    references_livros,
    references_anais
  ) %>%
  data.frame()
```

```{r retratacoes, cache = TRUE, cache.path = "cache/retratacoes/", eval = any(has.producao.sucupira, has.producao.ppg)}
doi_with_altmetric_retracted <- c()
if (!sjmisc::is_empty(doi_with_altmetric_all)) {
  for (i in 1:dim(doi_with_altmetric_all)[1]) {
    has.retraction <- data.frame(retracted = NA)
    try(has.retraction <- retractcheck::query_or(doi_with_altmetric_all$doi[i]), silent = TRUE)
    if (!is.na(has.retraction$retracted)) {
      doi_with_altmetric_retracted <-
        rbind(doi_with_altmetric_retracted,
              doi_with_altmetric_all[i,])
    }
  }
}

doi_without_altmetric_retracted <- c()
if (!sjmisc::is_empty(doi_without_altmetric_all)) {
  for (i in 1:dim(doi_without_altmetric_all)[1]) {
    has.retraction <- data.frame(retracted = NA)
    try(has.retraction <- retractcheck::query_or(doi_without_altmetric_all$doi[i]), silent = TRUE)
    if (!is.na(has.retraction$retracted)) {
      doi_without_altmetric_retracted <-
        rbind(doi_without_altmetric_retracted,
              doi_without_altmetric_all[i,])
    }
  }
}

# bind retractions
doi_retracted_all <-
  dplyr::bind_rows(
    doi_with_altmetric_retracted,
    doi_without_altmetric_retracted
  ) %>%
  as.data.frame()

has.retratacoes <- !sjmisc::is_empty(doi_retracted_all)

# check if there are retractions
if (has.retratacoes) {
# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(
      doi_with_altmetric_retracted$doi,
      doi_without_altmetric_retracted$doi
    ),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_retracted <-
  formatted_citations %>%
  data.frame()
} else {
  references_retracted <- data.frame()
}
```

```{r has, cache = TRUE, cache.path = "cache/has/"}
# directories
has.sucupira.files <- as.logical(has.sucupira.files)
has.ppg.files <- as.logical(has.ppg.files)
has.impacto.sage.files <- as.logical(has.impacto.sage.files)

# PPG files
has.agendas.pesquisa <- as.logical(has.agendas.pesquisa)
has.apresentacao <- as.logical(has.apresentacao)
has.area.capes <- as.logical(has.area.capes)
has.autoavaliacao <- as.logical(has.autoavaliacao)
has.avaliacao <- as.logical(has.avaliacao)
has.bibliografia <- as.logical(has.bibliografia)
has.blogs.externos <- as.logical(has.blogs.externos)
has.blog.ies <- as.logical(has.blog.ies)
has.bolsas <- as.logical(has.bolsas)
has.calendarios <- as.logical(has.calendarios)
has.cep <- as.logical(has.cep)
has.convenios <- as.logical(has.convenios)
has.cooperacoes <- as.logical(has.cooperacoes)
has.coordenacao <- as.logical(has.coordenacao)
has.dados.cadastrais <- as.logical(has.dados.cadastrais)
has.destaques <- as.logical(has.destaques)
has.discentes <- as.logical(has.discentes)
has.downloads <- as.logical(has.downloads)
has.editais <- as.logical(has.editais)
has.financiadores <- as.logical(has.financiadores)
has.grupos.pesquisa <- as.logical(has.grupos.pesquisa)
has.historico <- as.logical(has.historico)
has.infraestrutura <- as.logical(has.infraestrutura)
has.internacionalizacao <- as.logical(has.internacionalizacao)
has.laboratorios <- as.logical(has.laboratorios)
has.metodologia <- as.logical(has.metodologia)
has.notas <- as.logical(has.notas)
has.periodicos <- as.logical(has.periodicos)
has.planejamento <- as.logical(has.planejamento)
has.podcasts <- as.logical(has.podcasts)
has.politicas <- as.logical(has.politicas)
has.premios <- as.logical(has.premios)
has.premio.capes <- as.logical(has.premio.capes)
has.producao <- as.logical(has.producao)
has.repositorios.cooperacao <- as.logical(has.repositorios.cooperacao)
has.repositorios.sede <- as.logical(has.repositorios.sede)
has.videos <- as.logical(has.videos)

# data sucupira
has.artigos.completos.sucupira <- as.logical(has.artigos.completos.sucupira)
has.editoria.sucupira <- as.logical(has.editoria.sucupira)
has.livros.sucupira <- as.logical(has.livros.sucupira)
has.anais.sucupira <- as.logical(has.anais.sucupira)
has.producao.sucupira <- as.logical(has.producao.sucupira)
has.2024.2021 <- as.logical(has.2024.2021)
has.2020.2017 <- as.logical(has.2020.2017)
has.2016.2013 <- as.logical(has.2016.2013)
has.2012.2010 <- as.logical(has.2012.2010)
has.posdocs <- as.logical(has.posdocs)

# data ppg
has.artigos.completos.ppg <- as.logical(has.artigos.completos.ppg)
has.editoria.ppg <- as.logical(has.editoria.ppg)
has.livros.ppg <- as.logical(has.livros.ppg)
has.anais.ppg <- as.logical(has.anais.ppg)
has.producao.ppg <- as.logical(has.producao.ppg)

# external data
has.retratacoes <- as.logical(has.retratacoes)
```

```{r save, eval = FALSE}
# Write doi_with_altmetric_all to TSV file
try(
  write.table(
    doi_with_altmetric_all,
    "doi_with_altmetric_all.tsv",
    quote = FALSE,
    sep = "\t",
    row.names = FALSE,
    col.names = TRUE
  ),
  silent = TRUE
)

# Write doi_without_altmetric_all to TSV file
try(
  write.table(
    doi_without_altmetric_all,
    "doi_without_altmetric_all.tsv",
    quote = FALSE,
    sep = "\t",
    row.names = FALSE,
    col.names = TRUE
  ),
  silent = TRUE
)

# Write doi_all to TSV file
try(
  write.table(
    doi_all,
    "doi_all.tsv",
    quote = FALSE,
    sep = "\t",
    row.names = FALSE,
    col.names = TRUE
  ),
  silent = TRUE
)
```

```{r session-info}
sessioninfo::session_info() %>%
  details::details(summary = 'Current session info',
                   open = FALSE)
```
